#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HealthAndCat.Resource", IsApplication=true)]

namespace HealthAndCat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bowling = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int boy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cannedfood = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cheese = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int chickenleg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int egg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int golf = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int grain = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int leftarrowangle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int moon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int piggybank = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int roastchicken = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int screenshot83 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int splash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sun = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sunny = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int videocamera = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int woman = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060029
			public const int Bowling = 2131099689;
			
			// aapt resource value: 0x7f060041
			public const int BowlingText = 2131099713;
			
			// aapt resource value: 0x7f060035
			public const int Buy1 = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int Buy2 = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int Buy3 = 2131099705;
			
			// aapt resource value: 0x7f06003b
			public const int Buy4 = 2131099707;
			
			// aapt resource value: 0x7f06003d
			public const int Buy5 = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int Buy6 = 2131099711;
			
			// aapt resource value: 0x7f060042
			public const int Buy7 = 2131099714;
			
			// aapt resource value: 0x7f060045
			public const int Buy8 = 2131099717;
			
			// aapt resource value: 0x7f060048
			public const int Buy9 = 2131099720;
			
			// aapt resource value: 0x7f06001a
			public const int Cheese = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int Chicken = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int Eggs = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int Fish = 2131099683;
			
			// aapt resource value: 0x7f060015
			public const int Foods = 2131099669;
			
			// aapt resource value: 0x7f06002d
			public const int Golf = 2131099693;
			
			// aapt resource value: 0x7f060047
			public const int GolfText = 2131099719;
			
			// aapt resource value: 0x7f060044
			public const int MovieText = 2131099716;
			
			// aapt resource value: 0x7f06002b
			public const int Movies = 2131099691;
			
			// aapt resource value: 0x7f060017
			public const int Oats = 2131099671;
			
			// aapt resource value: 0x7f060036
			public const int Sell1 = 2131099702;
			
			// aapt resource value: 0x7f060038
			public const int Sell2 = 2131099704;
			
			// aapt resource value: 0x7f06003a
			public const int Sell3 = 2131099706;
			
			// aapt resource value: 0x7f06003c
			public const int Sell4 = 2131099708;
			
			// aapt resource value: 0x7f06003e
			public const int Sell5 = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int Sell6 = 2131099712;
			
			// aapt resource value: 0x7f060043
			public const int Sell7 = 2131099715;
			
			// aapt resource value: 0x7f060046
			public const int Sell8 = 2131099718;
			
			// aapt resource value: 0x7f060049
			public const int Sell9 = 2131099721;
			
			// aapt resource value: 0x7f060028
			public const int Toys = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int Turkey = 2131099686;
			
			// aapt resource value: 0x7f060018
			public const int Use1 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int Use2 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int Use3 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int Use4 = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int Use5 = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int Use6 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int Use7 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int Use8 = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int Use9 = 2131099694;
			
			// aapt resource value: 0x7f060010
			public const int button1 = 2131099664;
			
			// aapt resource value: 0x7f060032
			public const int button2 = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int button3 = 2131099697;
			
			// aapt resource value: 0x7f060034
			public const int characterName = 2131099700;
			
			// aapt resource value: 0x7f060007
			public const int editText1 = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int gridLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int gridLayout2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int imageButton1 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int imageView1 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int imageView2 = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int imageView3 = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int imageView4 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int imageView5 = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int imageView6 = 2131099685;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout2 = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout3 = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout4 = 2131099649;
			
			// aapt resource value: 0x7f06002f
			public const int linearLayout5 = 2131099695;
			
			// aapt resource value: 0x7f06000c
			public const int radioButton1 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int radioButton2 = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int radioGroup1 = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int space1 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int space2 = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int space3 = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int textView3 = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int textView4 = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int textView5 = 2131099650;
			
			// aapt resource value: 0x7f060033
			public const int textView6 = 2131099699;
			
			// aapt resource value: 0x7f060030
			public const int textView7 = 2131099696;
			
			// aapt resource value: 0x7f060014
			public const int toggleButton1 = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Creator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Inventory = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Store = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
